/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SubmitRequestListApproverGet$Params {

/**
 * The page number to retrieve
 */
  pagenumber?: number;

/**
 * The number of items per page
 */
  pagesize?: number;

/**
 * WAITING/CONFIRM/REJECT
 */
  status?: string;

/**
 * BIZDEV
 */
  type?: string;

/**
 * tienpm
 */
  approver?: string;

/**
 * tienpm
 */
  supervisor?: string;
}

export function submitRequestListApproverGet(http: HttpClient, rootUrl: string, params?: SubmitRequestListApproverGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{

/**
 * The current page number
 */
'pageNumber'?: number;

/**
 * The number of items per page
 */
'pageSize'?: number;

/**
 * The total number of items
 */
'totalItems'?: number;

/**
 * The total number of pages
 */
'totalPages'?: number;
'data'?: Array<{

/**
 * The account name of the user
 */
'accountName'?: string;

/**
 * The total score of the user
 */
'totalScore'?: string;

/**
 * The rank of the user
 */
'rank'?: number;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, submitRequestListApproverGet.PATH, 'get');
  if (params) {
    rb.query('pagenumber', params.pagenumber, {});
    rb.query('pagesize', params.pagesize, {});
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('approver', params.approver, {});
    rb.query('supervisor', params.supervisor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      
      /**
       * The current page number
       */
      'pageNumber'?: number;
      
      /**
       * The number of items per page
       */
      'pageSize'?: number;
      
      /**
       * The total number of items
       */
      'totalItems'?: number;
      
      /**
       * The total number of pages
       */
      'totalPages'?: number;
      'data'?: Array<{
      
      /**
       * The account name of the user
       */
      'accountName'?: string;
      
      /**
       * The total score of the user
       */
      'totalScore'?: string;
      
      /**
       * The rank of the user
       */
      'rank'?: number;
      }>;
      }>;
    })
  );
}

submitRequestListApproverGet.PATH = '/submit-request/list-approver';
