/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UsersMeGet$Params {
}

export function usersMeGet(http: HttpClient, rootUrl: string, params?: UsersMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
'payload'?: {

/**
 * The user avatar
 */
'avatar'?: string;

/**
 * The user email
 */
'email'?: string;

/**
 * The user fullName
 */
'fullName'?: string;

/**
 * The user token
 */
'token'?: string;
};
}>> {
  const rb = new RequestBuilder(rootUrl, usersMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      'payload'?: {
      
      /**
       * The user avatar
       */
      'avatar'?: string;
      
      /**
       * The user email
       */
      'email'?: string;
      
      /**
       * The user fullName
       */
      'fullName'?: string;
      
      /**
       * The user token
       */
      'token'?: string;
      };
      }>;
    })
  );
}

usersMeGet.PATH = '/users/me';
