/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UsersPut$Params {
      body?: {

/**
 * The user identity card front face, upload type jpg|jpeg|png
 */
'identityCardFront'?: Blob;

/**
 * The user identity card back face, upload type jpg|jpeg|png
 */
'identityCardBack'?: Blob;

/**
 * The user avatar, upload type jpg|jpeg|png
 */
'avatar'?: Blob;

/**
 * The user cover, upload type jpg|jpeg|png
 */
'cover'?: Blob;

/**
 * The body stringify information
 */
'data'?: string;
}
}

export function usersPut(http: HttpClient, rootUrl: string, params?: UsersPut$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'success'?: boolean;
}>> {
  const rb = new RequestBuilder(rootUrl, usersPut.PATH, 'put');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'success'?: boolean;
      }>;
    })
  );
}

usersPut.PATH = '/users';
