export enum PopupType {
  CONFIRM = 'CONFIRM',
  CONFIRM_DELETE = 'CONFIRM_DELETE',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  FAILED = 'RESTART_FAILED',
  ACTIONS_SUCCESS = 'ACTIONS_SUCCESS',
  LOGOUT = 'LOGOUT'
}

export enum ConfirmActionType {
  APPLY = 'CONFIRM',
  RESTART = 'CONFIRM_DELETE',
  START = 'SUCCESS',
  STOP = 'WARNING',
  DELETE = 'RESTART_FAILED',
  NONE = 'ACTIONS_SUCCESS',
}
