version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dss_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db/dss_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: