/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Category {

  /**
   * A short description of the category
   */
  description?: string;

  /**
   * The name of the category
   */
  name?: string;

  /**
   * The score associated with the category
   */
  score?: number;

  /**
   * The type of the category
   */
  type?: string;
}
