/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {

  /**
   * Email address of the user
   */
  email?: string;

  /**
   * first Name of the user
   */
  firstName?: string;

  /**
   * Unique identifier for the user
   */
  id?: string;

  /**
   * last Name of the user
   */
  lastName?: string;
}
