/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ValidatorErrorItem {

  /**
   * The location of value
   */
  location?: string;

  /**
   * The error message
   */
  msg?: string;

  /**
   * The key of value
   */
  param?: string;

  /**
   * The value got on request
   */
  value?: string;
}
