// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  aiSupport: true,
  isCustomerConfig: true,
  version: env.npm_package_version,
  rootUrl: $ENV.API_URL || 'http://172.24.10.29:8000/api/v1',
  defaultLanguage: 'vi',
  supportedLanguages: ['en', 'vi'],
  secret: '1233ads222FDDSFSD!#@',
  afterLogged: {
    customerAdmin: '',
    default: '',
  },
  packageConfig: [
    {
      package: 'security-monitoring',
      restrictMenu: ['/package/security-monitoring/live-monitoring'],
      restrictFeatures: [
        'SMCameraLiveStreaming',
        'SMTimeWarningConfig',
        'SMAlertList',
        'IotConfig',
        'reportSpaceZone',
        'managerInFence',
      ],
      allowDirectNotify: false,
    },
  ],
  pageSize: 12,
};
