// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  hmr: true,
  aiSupport: true,
  isCustomerConfig: true,
  version: env.npm_package_version + '-dev',
  rootUrl: $ENV.API_URL || 'http://localhost:3001/v1',
  defaultLanguage: 'vi',
  supportedLanguages: ['en', 'vi'],
  pageSize: 12,
  afterLogged: {
    customerAdmin: '',
    default: '',
  },
  packageConfig: [
    {
      package: 'security-monitoring',
      restrictMenu: ['/package/security-monitoring/live-monitoring'],
      restrictFeatures: [
        'SMCameraLiveStreaming',
        'SMTimeWarningConfig',
        'SMAlertList',
        'IotConfig',
        'reportSpaceZone',
        'managerInFence',
      ],
      allowDirectNotify: false,
    },
  ],
  secret: '1233ads222FDDSFSD!#@',
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
